# Generated by Django 5.0.3 on 2024-03-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='web3event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('source_url', models.CharField(max_length=100)),
                ('event_url', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=300)),
                ('description', models.CharField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
