# Generated by Django 5.0.3 on 2024-04-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web3event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='web3event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='web3event',
            name='event_url',
        ),
        migrations.RemoveField(
            model_name='web3event',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='web3event',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='web3event',
            name='time_zone',
        ),
        migrations.AlterField(
            model_name='web3event',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
